{% set data = load_setup_py_data() %}

package:
  name: cpacs2to3
  version: {{ data.get('version') }}

source:
  git_url: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - tigl3
    - tigl
    - tixi
    - tixi3
    - numpy

test:
  imports:
    - cpacs2to3

  commands:
    - cpacs2to3 --help

about:
  home:  https://github.com/DLR-SC/cpacs2to3
  license: Apache 2.0
