sudo: false

language: minimal

git:
  depth: false

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi;
  - chmod +x miniconda.sh
  - yes | ./miniconda.sh -b -p $HOME/miniconda
  - export PYTHONUNBUFFERED=1
  - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build gitpython anaconda-client
  - conda config --add channels https://conda.anaconda.org/dlr-sc
  - conda config --add channels https://conda.anaconda.org/dlr-sc/label/tigl-dev
  

script:
  - conda build ci/conda --user DLR-SC --token $ANACONDA_API_TOKEN
